import type { ContentItem } from './types';

// Mock data for when TMDB API key is not configured
// Uses real TMDB image paths that work with the image CDN
export const MOCK_GENRES = [
  { id: 28, name: 'Action' },
  { id: 35, name: 'Comedy' },
  { id: 18, name: 'Drama' },
  { id: 878, name: 'Sci-Fi' },
  { id: 53, name: 'Thriller' },
  { id: 27, name: 'Horror' },
  { id: 10749, name: 'Romance' },
  { id: 16, name: 'Animation' },
  { id: 99, name: 'Documentary' },
  { id: 14, name: 'Fantasy' },
  { id: 10765, name: 'Sci-Fi & Fantasy' },
  { id: 10759, name: 'Action & Adventure' },
  { id: 80, name: 'Crime' },
  { id: 9648, name: 'Mystery' },
];

export const MOCK_CONTENT: ContentItem[] = [
  // ================= MOVIES =================
  {
    id: 157336,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK1DVfjko.jpg',
    releaseYear: '2014',
    rating: 8.4,
    voteCount: 34521,
    genreIds: [878, 18, 10765],
    mediaType: 'movie',
    trailerKey: 'zSWdZVtXT7E',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son Michael steps in.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseYear: '1972',
    rating: 8.7,
    voteCount: 19876,
    genreIds: [18, 80],
    mediaType: 'movie',
    trailerKey: 'UaVTIH8mujA',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 550,
    title: 'Fight Club',
    overview: 'A ticking-time-bomb and insomnia-ridden office employee and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hZkgoQYus5dXo3H8T7CYV18sAor.jpg',
    releaseYear: '1999',
    rating: 8.4,
    voteCount: 28034,
    genreIds: [18, 53],
    mediaType: 'movie',
    trailerKey: 'qtRKdVHc-cE',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ly8OI269tfgPN0H070g5CY3697v.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    releaseYear: '1994',
    rating: 8.7,
    voteCount: 26500,
    genreIds: [18, 80],
    mediaType: 'movie',
    trailerKey: 'PLl99DlL6b4',
    providers: [],
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseYear: '1994',
    rating: 8.5,
    voteCount: 27234,
    genreIds: [53, 80],
    mediaType: 'movie',
    trailerKey: 's7EdQ4FqbhY',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911kpUpFoagJx3m.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg',
    releaseYear: '2008',
    rating: 8.5,
    voteCount: 32100,
    genreIds: [28, 80, 18, 10759],
    mediaType: 'movie',
    trailerKey: 'EXeTwQWrcwY',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 13,
    title: 'Forrest Gump',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events — in each case, far exceeding what anyone imagined he could do.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    releaseYear: '1994',
    rating: 8.5,
    voteCount: 26800,
    genreIds: [35, 18, 10749],
    mediaType: 'movie',
    trailerKey: 'bLvqoHBptjg',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 120,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    overview: 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/pIUvQ9Ed35wlWhY2oU6OmwEgzx.jpg',
    releaseYear: '2001',
    rating: 8.4,
    voteCount: 24300,
    genreIds: [14, 28, 10759, 10765],
    mediaType: 'movie',
    trailerKey: 'V75dMMIW2B4',
    providers: [],
  },
  {
    id: 603,
    title: 'The Matrix',
    overview: 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    releaseYear: '1999',
    rating: 8.2,
    voteCount: 25600,
    genreIds: [28, 878, 10759, 10765],
    mediaType: 'movie',
    trailerKey: 'vKQi3bBA1y8',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 429,
    title: 'The Good, the Bad and the Ugly',
    overview: 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the Southwest in search of gold.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hMnAJkf0K4VbhbcGiq7R3o6jnHR.jpg',
    releaseYear: '1966',
    rating: 8.5,
    voteCount: 8200,
    genreIds: [18, 28, 10759],
    mediaType: 'movie',
    trailerKey: 'WCN5JJY_wiA',
    providers: [],
  },
  {
    id: 823464,
    title: 'Godzilla x Kong: The New Empire',
    overview: 'Following their fight, Godzilla and Kong make an uneasy truce. However, a colossal undiscovered threat, hidden deep within our world, challenges their very existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDV4jC1kCTAM5BN.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg',
    releaseYear: '2024',
    rating: 7.1,
    voteCount: 5200,
    genreIds: [28, 878, 10759, 10765],
    mediaType: 'movie',
    trailerKey: 'lV1OOlGwExM',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 572802,
    title: 'Aquaman and the Lost Kingdom',
    overview: 'Black Manta seeks revenge on Aquaman for the death of his father, while wielding the power of the mythic Black Trident. To defeat him, Aquaman turns to his imprisoned brother Orm.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8xV47NDrjdZDpkVcCFqkdHa3T5C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/cnqwv5Uz3UW5f086IWbQKr3yyJz.jpg',
    releaseYear: '2023',
    rating: 6.3,
    voteCount: 3800,
    genreIds: [28, 14, 10759, 10765],
    mediaType: 'movie',
    providers: [],
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    releaseYear: '2024',
    rating: 8.2,
    voteCount: 8100,
    genreIds: [878, 10765, 28, 10759],
    mediaType: 'movie',
    trailerKey: 'Way9Dexny3w',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 138843,
    title: 'The Conjuring',
    overview: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their secluded farmhouse.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/w9kR8qbm2yo6L661wFGDV0YjDty.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5GB26w3z2kuv7SRn68B5t5vSMRc.jpg',
    releaseYear: '2013',
    rating: 7.5,
    voteCount: 10500,
    genreIds: [27, 9648, 53],
    mediaType: 'movie',
    trailerKey: 'k10ETZ42q5o',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 377,
    title: 'A Nightmare on Elm Street',
    overview: 'The monstrous spirit of a slain child murderer seeks revenge by invading the dreams of teenagers whose parents were responsible for his demise.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wEvhx5F244nsH1r35447Sv8gbGB.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/x26E0iL596Z586pWl9bM900Q7mE.jpg',
    releaseYear: '1984',
    rating: 7.3,
    voteCount: 4800,
    genreIds: [27, 9648],
    mediaType: 'movie',
    trailerKey: 'dCVh4lBfW-c',
    providers: [],
  },
  {
    id: 419430,
    title: 'Get Out',
    overview: 'Chris and his girlfriend Rose go upstate to visit her parents. At first, Chris reads their overly accommodating behavior as nervous attempts to deal with their interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he could never have imagined.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1swQA5LJ4pqZ45778zs8Vz36HYs.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ocUrn7j6M2v7copgGK7kgqal23L.jpg',
    releaseYear: '2017',
    rating: 7.6,
    voteCount: 15600,
    genreIds: [27, 9648, 53],
    mediaType: 'movie',
    trailerKey: 'sRfnebToDRA',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 346364,
    title: 'It',
    overview: 'In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9E2y6li6Z98rTE7bfYq0mgG0tTx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tcheoA2n6X2452v2X7gR87tCc9x.jpg',
    releaseYear: '2017',
    rating: 7.2,
    voteCount: 22000,
    genreIds: [27, 53, 14, 10765],
    mediaType: 'movie',
    trailerKey: 'FnCdO0ipJow',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 515042,
    title: 'Free Solo',
    overview: 'Alex Honnold attempts to conquer the first free solo climb of the famed El Capitan\'s 3,000-foot vertical rock face in Yosemite National Park.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d4K445T3shkS22j9g5t2V746K15.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7F5f070mJ669wA76a9x0ePvxN3c.jpg',
    releaseYear: '2018',
    rating: 8.0,
    voteCount: 1200,
    genreIds: [99],
    mediaType: 'movie',
    trailerKey: 'urRVZ4SW7WU',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 673191,
    title: 'My Octopus Teacher',
    overview: 'A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wP1NnU6A0u0264e1cR1n9B890kF.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8j32d00G003A4uD23S9g1cW1yD3.jpg',
    releaseYear: '2020',
    rating: 8.1,
    voteCount: 950,
    genreIds: [99],
    mediaType: 'movie',
    trailerKey: '3s0LTDhqe5A',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 656561,
    title: 'The Social Dilemma',
    overview: 'This documentary-drama hybrid explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cjOl5tB6a6PM5Xmq59n5OFii07v.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/28f8n41N9Dq77YvY457788P890K.jpg',
    releaseYear: '2020',
    rating: 7.5,
    voteCount: 1900,
    genreIds: [99, 18],
    mediaType: 'movie',
    trailerKey: 'uaaC57tcci0',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 469,
    title: 'March of the Penguins',
    overview: 'In the Antarctic, every autumn, all the penguins of breeding age leave the ocean and walk for days to their traditional nesting grounds to breed.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9e0p7G5A9F0DqP1QkP1j5C5C2E.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7F5f070mJ669wA76a9x0ePvxN3c.jpg',
    releaseYear: '2005',
    rating: 7.4,
    voteCount: 1500,
    genreIds: [99],
    mediaType: 'movie',
    providers: [],
  },
  {
    id: 129,
    title: 'Spirited Away',
    overview: 'A young girl, Chihiro, becomes trapped in a mysterious spirit world. After her parents are transformed into pigs, she must work in a bathhouse to find a way to free them.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/393MtUUiIbZ5uH4PGSRwZ0Ypvy3.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/m03nJy72Jnsm0EOAAW7sGEvJU3s.jpg',
    releaseYear: '2001',
    rating: 8.5,
    voteCount: 15800,
    genreIds: [16, 14, 18, 10765],
    mediaType: 'movie',
    trailerKey: 'ByXuk9QqQkk',
    providers: [],
  },
  {
    id: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    overview: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat to all realities.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiRs6wP9Nh474JZIS2Vd2k2kr0g.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7d6x1xSfEX7tr93J46Z6iObiZsn.jpg',
    releaseYear: '2018',
    rating: 8.4,
    voteCount: 14200,
    genreIds: [16, 28, 14, 878, 10759, 10765],
    mediaType: 'movie',
    trailerKey: 'tg52up16eq0',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 862,
    title: 'Toy Story',
    overview: 'Led by Woody, Andy\'s toys live happily in his room until Andy\'s birthday brings Buzz Lightyear onto the scene. Fearful of losing his place, Woody plots against Buzz.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4m4jHcn0zLYA34JTYZ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/vxGkPZ99t1fD732gC45Y268D7iM.jpg',
    releaseYear: '1995',
    rating: 8.0,
    voteCount: 17000,
    genreIds: [16, 35, 14, 10765],
    mediaType: 'movie',
    trailerKey: 'CxwTL_v10S4',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 354912,
    title: 'Coco',
    overview: 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gGe2uBwH6j875a6tQQY704u2f2k.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/askg6SM2ee7jUiVj2RjaRyp4RdB.jpg',
    releaseYear: '2017',
    rating: 8.2,
    voteCount: 18100,
    genreIds: [16, 14, 35, 10765, 18],
    mediaType: 'movie',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    overview: 'After reuniting with Gwen Stacy, Brooklyn\'s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8VtB7mgoGJgX2l6pdCEwroa1V5C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/4Hod5Gu55c4dUU7q4cCXkCj6N1v.jpg',
    releaseYear: '2023',
    rating: 8.4,
    voteCount: 6500,
    genreIds: [16, 28, 878, 10759, 10765],
    mediaType: 'movie',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 313369,
    title: 'La La Land',
    overview: 'Mia, an aspiring actress, and Sebastian, a dedicated jazz musician, struggle to make ends meet in a city known for crushing hopes and breaking hearts.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uC6TTN1Rxj6v2bg2FaY5eSGScaG.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2t71s2gX3jQ0y4H9mNnQkG7y3t.jpg',
    releaseYear: '2016',
    rating: 7.9,
    voteCount: 15900,
    genreIds: [10749, 35, 18],
    mediaType: 'movie',
    trailerKey: '0pdqf4K9Of8',
    providers: [],
  },
  {
    id: 11020,
    title: 'The Notebook',
    overview: 'An epic love story centered around an older man who reads aloud to a woman with Alzheimer\'s from a faded notebook that contains their own romantic journey.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rNzQyJleX4jZ7JW72hgg39t5vSMR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    releaseYear: '2004',
    rating: 7.9,
    voteCount: 10800,
    genreIds: [10749, 18],
    mediaType: 'movie',
    trailerKey: 'yDJIcYE32NU',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 597,
    title: 'Titanic',
    overview: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9xjZS243rCl7scU7Qhy5q1qSjZ9.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/6Km1Hw3K2K8fX5QoEaP7y3d8R1k.jpg',
    releaseYear: '1997',
    rating: 7.9,
    voteCount: 23000,
    genreIds: [10749, 18, 53],
    mediaType: 'movie',
    trailerKey: 'CHekzSiZjrY',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 18785,
    title: 'The Hangover',
    overview: 'Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the bachelor missing. They make their way back in search of their friend.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1e4A22Xm0v7q32hW77c8p844n5e.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/28f8n41N9Dq77YvY457788P890K.jpg',
    releaseYear: '2009',
    rating: 7.3,
    voteCount: 16000,
    genreIds: [35],
    mediaType: 'movie',
    trailerKey: 'tcdUj-P-S48',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 8363,
    title: 'Superbad',
    overview: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a beer-soaked party goes awry.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ek8goz3x2kuv7SRn68B5t5vSMRc.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5GB26w3z2kuv7SRn68B5t5vSMRc.jpg',
    releaseYear: '2007',
    rating: 7.2,
    voteCount: 6800,
    genreIds: [35],
    mediaType: 'movie',
    trailerKey: 'N_AS67Fz3sQ',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 11324,
    title: 'Shutter Island',
    overview: 'A US Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane, while experiencing hallucinations.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/42Nz84DAZATv714J2j3aUqZ2iH7.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseYear: '2010',
    rating: 8.2,
    voteCount: 22100,
    genreIds: [18, 53, 9648],
    mediaType: 'movie',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 546554,
    title: 'Knives Out',
    overview: 'When renowned crime novelist Harlan Thrombey is found dead at his estate, the inquisitive Detective Benoit Blanc is mysteriously enlisted to investigate.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3kHg9V2h5Jcxz5nK46pq6hyjW5G.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/askg6SM2ee7jUiVj2RjaRyp4RdB.jpg',
    releaseYear: '2019',
    rating: 7.9,
    voteCount: 14000,
    genreIds: [35, 9648, 53],
    mediaType: 'movie',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },

  // ================= TV SERIES =================
  {
    id: 1396,
    title: 'Breaking Bad',
    overview: 'When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live, he becomes filled with a sense of fearlessness.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ztK6o1wG6Ma2vC624UHGQ25YGC.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseYear: '2008',
    rating: 8.9,
    voteCount: 13500,
    genreIds: [18, 80, 53],
    mediaType: 'tv',
    trailerKey: 'HhesaQXLuRY',
    numberOfSeasons: 5,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1399,
    title: 'Game of Thrones',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    releaseYear: '2011',
    rating: 8.4,
    voteCount: 22100,
    genreIds: [10765, 18, 10759, 14, 28],
    mediaType: 'tv',
    trailerKey: 'KPLWWIOCOOQ',
    numberOfSeasons: 8,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 66732,
    title: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/56v2KjBlYj4fOhLEnDAJZRLoAVb.jpg',
    releaseYear: '2016',
    rating: 8.6,
    voteCount: 17800,
    genreIds: [18, 10765, 9648, 27, 53, 878, 14],
    mediaType: 'tv',
    trailerKey: 'b9EkMc79ZSU',
    numberOfSeasons: 5,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 94605,
    title: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    releaseYear: '2021',
    rating: 8.7,
    voteCount: 4500,
    genreIds: [16, 10765, 10759, 14, 28],
    mediaType: 'tv',
    trailerKey: 'fXmAurh012s',
    numberOfSeasons: 2,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 100088,
    title: 'The Last of Us',
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie out of an oppressive quarantine zone.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    releaseYear: '2023',
    rating: 8.6,
    voteCount: 5800,
    genreIds: [18, 10765, 10759, 28, 878, 14],
    mediaType: 'tv',
    trailerKey: 'uLtkt8BonwM',
    numberOfSeasons: 2,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 76479,
    title: 'The Boys',
    overview: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers rather than using them for good.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9Ev8YwoozdMPcH8III.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7q448EVOnuE3gVAx24krzO7SNXM.jpg',
    releaseYear: '2019',
    rating: 8.5,
    voteCount: 10200,
    genreIds: [10765, 10759, 28, 878],
    mediaType: 'tv',
    trailerKey: 'tcrNsIaQkb4',
    numberOfSeasons: 4,
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 114461,
    title: 'Ahsoka',
    overview: 'Former Jedi Knight Ahsoka Tano investigates an emerging threat to a vulnerable galaxy after the fall of the Galactic Empire.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/laCJxobHoPVaIMToJhkqYuXdPWV.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kUaFsOFtfCN3Jk2yP9GLnVr1CxI.jpg',
    releaseYear: '2023',
    rating: 7.4,
    voteCount: 2800,
    genreIds: [10765, 10759, 18, 28, 878],
    mediaType: 'tv',
    trailerKey: 'JDKc3eVTVmY',
    numberOfSeasons: 1,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 2316,
    title: 'The Office',
    overview: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/77Refo15tFwyR9NPQ5vpzxTj19Q.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2t71s2gX3jQ0y4H9mNnQkG7y3t.jpg',
    releaseYear: '2005',
    rating: 8.6,
    voteCount: 9800,
    genreIds: [35, 18],
    mediaType: 'tv',
    numberOfSeasons: 9,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1668,
    title: 'Friends',
    overview: 'Six young people navigate their personal and professional lives in Manhattan, sharing their romances, struggles, and laughs in this iconic sitcom.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f4961Z3gO2hbHG6MUJg2Z2R7Bhv.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    releaseYear: '1994',
    rating: 8.5,
    voteCount: 10500,
    genreIds: [35, 10749],
    mediaType: 'tv',
    numberOfSeasons: 10,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 48891,
    title: 'Brooklyn Nine-Nine',
    overview: 'A comedy following the exploits of Detective Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/185g9V2h5Jcxz5nK46pq6hyjW5G.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5GB26w3z2kuv7SRn68B5t5vSMRc.jpg',
    releaseYear: '2013',
    rating: 8.2,
    voteCount: 6500,
    genreIds: [35, 80],
    mediaType: 'tv',
    numberOfSeasons: 8,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 60625,
    title: 'Rick and Morty',
    overview: 'An animated series that follows the exploits of a super scientist and his easily influenced grandson, traveling across alternate dimensions.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cvHN8gB5t5vSMRcwP1NnU6A0u02.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    releaseYear: '2013',
    rating: 8.7,
    voteCount: 9200,
    genreIds: [16, 35, 10765, 878],
    mediaType: 'tv',
    numberOfSeasons: 7,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 19885,
    title: 'Sherlock',
    overview: 'A modern update finds the famous sleuth and his doctor partner solving bizarre crimes in 21st century London with brilliance and high technology.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/78Refo15tFwyR9NPQ5vpzxTj19Q.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseYear: '2010',
    rating: 8.5,
    voteCount: 8200,
    genreIds: [80, 9648, 18, 53],
    mediaType: 'tv',
    numberOfSeasons: 4,
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 93405,
    title: 'Squid Game',
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseYear: '2021',
    rating: 7.8,
    voteCount: 14200,
    genreIds: [28, 18, 53, 10759],
    mediaType: 'tv',
    numberOfSeasons: 2,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 70523,
    title: 'Dark',
    overview: 'A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/apbrVmWg8w2XxtZBy8w8th54KBA.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    releaseYear: '2017',
    rating: 8.4,
    voteCount: 5200,
    genreIds: [9648, 10765, 878, 53],
    mediaType: 'tv',
    numberOfSeasons: 3,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1402,
    title: 'The Walking Dead',
    overview: 'Sheriff\'s deputy Rick Grimes leads a group of survivors in a world overrun by zombies, fighting for survival against walking dead and living threats.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/n7P45778zs8Vz36HYsLJ4pqZ45.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/56v2KjBlYj4fOhLEnDAJZRLoAVb.jpg',
    releaseYear: '2010',
    rating: 8.1,
    voteCount: 15400,
    genreIds: [27, 10765, 18, 53],
    mediaType: 'tv',
    numberOfSeasons: 11,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1413,
    title: 'American Horror Story',
    overview: 'An anthology series centering on different characters and locations, including a murder house, an insane asylum, a witch coven, a freak show, and a hotel.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9E2y6li6Z98rTE7bfYq0mgG0tTx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tcheoA2n6X2452v2X7gR87tCc9x.jpg',
    releaseYear: '2011',
    rating: 8.0,
    voteCount: 5100,
    genreIds: [27, 9648, 18],
    mediaType: 'tv',
    numberOfSeasons: 12,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 80986,
    title: 'The Haunting of Hill House',
    overview: 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/w9kR8qbm2yo6L661wFGDV0YjDty.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ocUrn7j6M2v7copgGK7kgqal23L.jpg',
    releaseYear: '2018',
    rating: 8.6,
    voteCount: 3100,
    genreIds: [27, 9648, 18, 53],
    mediaType: 'tv',
    numberOfSeasons: 1,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 112888,
    title: 'Bridgerton',
    overview: 'Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uC6TTN1Rxj6v2bg2FaY5eSGScaG.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/28f8n41N9Dq77YvY457788P890K.jpg',
    releaseYear: '2020',
    rating: 8.1,
    voteCount: 3200,
    genreIds: [18, 10749],
    mediaType: 'tv',
    numberOfSeasons: 3,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 94796,
    title: 'Crash Landing on You',
    overview: 'A South Korean heiress accidentally paraglides into North Korea, where she is hidden by an army officer who falls in love with her.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiRs6wP9Nh474JZIS2Vd2k2kr0g.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/Askg6SM2ee7jUiVj2RjaRyp4RdB.jpg',
    releaseYear: '2019',
    rating: 8.7,
    voteCount: 1500,
    genreIds: [35, 18, 10749],
    mediaType: 'tv',
    numberOfSeasons: 1,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1416,
    title: 'Grey\'s Anatomy',
    overview: 'Follows the personal and professional lives of surgical interns, residents, and attendings at Seattle Grace Hospital.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/daG75FwyR9NPQ5vpzxTj19Q7rW.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/6Km1Hw3K2K8fX5QoEaP7y3d8R1k.jpg',
    releaseYear: '2005',
    rating: 8.2,
    voteCount: 9800,
    genreIds: [18, 10749],
    mediaType: 'tv',
    numberOfSeasons: 20,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 246,
    title: 'Avatar: The Last Airbender',
    overview: 'In a war-torn world of elemental magic, a young boy awakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9Ev8YwoozdMPcH8III.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/Askg6SM2ee7jUiVj2RjaRyp4RdB.jpg',
    releaseYear: '2005',
    rating: 8.7,
    voteCount: 3900,
    genreIds: [16, 10759, 14, 10765, 28],
    mediaType: 'tv',
    numberOfSeasons: 3,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1429,
    title: 'Attack on Titan',
    overview: 'Several hundred years ago, humans were nearly exterminated by giants. A small percentage of humanity survived by shutting themselves in a city protected by extremely high walls.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiRs6wP9Nh474JZIS2Vd2k2kr0g.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/vxGkPZ99t1fD732gC45Y268D7iM.jpg',
    releaseYear: '2013',
    rating: 8.7,
    voteCount: 5600,
    genreIds: [16, 28, 10759, 10765, 878],
    mediaType: 'tv',
    numberOfSeasons: 4,
    providers: [],
  },
  {
    id: 34391,
    title: 'Planet Earth',
    overview: 'David Attenborough narrates this landmark nine-part series exploring the earth\'s ultimate natural wonders and extreme animal environments.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d4K445T3shkS22j9g5t2V746K15.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7F5f070mJ669wA76a9x0ePvxN3c.jpg',
    releaseYear: '2006',
    rating: 8.8,
    voteCount: 1500,
    genreIds: [99],
    mediaType: 'tv',
    numberOfSeasons: 1,
    providers: [],
  },
  {
    id: 83870,
    title: 'Our Planet',
    overview: 'Experience our planet\'s natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cjOl5tB6a6PM5Xmq59n5OFii07v.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8j32d00G003A4uD23S9g1cW1yD3.jpg',
    releaseYear: '2019',
    rating: 8.8,
    voteCount: 900,
    genreIds: [99],
    mediaType: 'tv',
    numberOfSeasons: 2,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 98516,
    title: 'The Last Dance',
    overview: 'A 10-part documentary series detailing the career of Michael Jordan and the 1990s Chicago Bulls, featuring never-before-seen footage from the legendary 1997-98 season.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ztK6o1wG6Ma2vC624UHGQ25YGC.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5GB26w3z2kuv7SRn68B5t5vSMRc.jpg',
    releaseYear: '2020',
    rating: 8.7,
    voteCount: 1100,
    genreIds: [99, 18],
    mediaType: 'tv',
    numberOfSeasons: 1,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 86248,
    title: 'Formula 1: Drive to Survive',
    overview: 'Drivers, managers, and team owners live life in the fast lane – both on and off the track. A deep-dive documentary following every intense season of elite racing.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cjOl5tB6a6PM5Xmq59n5OFii07v.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseYear: '2019',
    rating: 8.1,
    voteCount: 800,
    genreIds: [99],
    mediaType: 'tv',
    numberOfSeasons: 6,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 60574,
    title: 'Peaky Blinders',
    overview: 'A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9Ev8YwoozdMPcH8III.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/28f8n41N9Dq77YvY457788P890K.jpg',
    releaseYear: '2013',
    rating: 8.5,
    voteCount: 9200,
    genreIds: [18, 80],
    mediaType: 'tv',
    numberOfSeasons: 6,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 74204,
    title: 'Mindhunter',
    overview: 'In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and uneasily getting too close to all-too-real monsters.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ek8goz3x2kuv7SRn68B5t5vSMRc.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5GB26w3z2kuv7SRn68B5t5vSMRc.jpg',
    releaseYear: '2017',
    rating: 8.4,
    voteCount: 4200,
    genreIds: [18, 80, 9648, 53],
    mediaType: 'tv',
    numberOfSeasons: 2,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 71446,
    title: 'Money Heist',
    overview: 'To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have single-name aliases.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ztK6o1wG6Ma2vC624UHGQ25YGC.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    releaseYear: '2017',
    rating: 8.3,
    voteCount: 18200,
    genreIds: [28, 80, 53, 10759],
    mediaType: 'tv',
    numberOfSeasons: 5,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 95396,
    title: 'Severance',
    overview: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives, sparking a quest to uncover the truth.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9Ev8YwoozdMPcH8III.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ocUrn7j6M2v7copgGK7kgqal23L.jpg',
    releaseYear: '2022',
    rating: 8.4,
    voteCount: 2200,
    genreIds: [18, 9648, 878, 10765, 53],
    mediaType: 'tv',
    numberOfSeasons: 2,
    providers: [],
  },
];

export function getMockContent(
  mediaType: 'movie' | 'tv' | 'all' = 'all',
  genreId?: number
): ContentItem[] {
  let filtered = MOCK_CONTENT;
  
  if (mediaType !== 'all') {
    filtered = filtered.filter(item => item.mediaType === mediaType);
  }
  
  if (genreId) {
    filtered = filtered.filter(item => item.genreIds.includes(genreId));
  }
  
  // Shuffle dynamically for infinite discovery feel
  return [...filtered].sort(() => Math.random() - 0.5);
}
