import type { ContentItem } from './types';

// Mock data for when TMDB API key is not configured
// Uses real TMDB image paths that work with the image CDN
export const MOCK_GENRES = [
  { id: 28, name: 'Action' },
  { id: 35, name: 'Comedy' },
  { id: 18, name: 'Drama' },
  { id: 878, name: 'Sci-Fi' },
  { id: 53, name: 'Thriller' },
  { id: 27, name: 'Horror' },
  { id: 10749, name: 'Romance' },
  { id: 16, name: 'Animation' },
  { id: 99, name: 'Documentary' },
  { id: 14, name: 'Fantasy' },
  { id: 10765, name: 'Sci-Fi & Fantasy' },
  { id: 10759, name: 'Action & Adventure' },
  { id: 80, name: 'Crime' },
  { id: 9648, name: 'Mystery' },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: 157336,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK1DVfjko.jpg',
    releaseYear: '2014',
    rating: 8.4,
    voteCount: 34521,
    genreIds: [878, 18, 12],
    mediaType: 'movie',
    trailerKey: 'zSWdZVtXT7E',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son Michael steps in.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseYear: '1972',
    rating: 8.7,
    voteCount: 19876,
    genreIds: [18, 80],
    mediaType: 'movie',
    trailerKey: 'UaVTIH8mujA',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 550,
    title: 'Fight Club',
    overview: 'A ticking-Loss-Loss and insomnia-Loss office employee and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hZkgoQYus5dXo3H8T7CYV18sAor.jpg',
    releaseYear: '1999',
    rating: 8.4,
    voteCount: 28034,
    genreIds: [18, 53],
    mediaType: 'movie',
    trailerKey: 'qtRKdVHc-cE',
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9cjIGRiQXPAOT2BLkwHqWZ4klAl.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    releaseYear: '1994',
    rating: 8.7,
    voteCount: 26500,
    genreIds: [18, 80],
    mediaType: 'movie',
    trailerKey: 'PLl99DlL6b4',
    providers: [],
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseYear: '1994',
    rating: 8.5,
    voteCount: 27234,
    genreIds: [53, 80],
    mediaType: 'movie',
    trailerKey: 's7EdQ4FqbhY',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911kpUpFoagJx3m.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg',
    releaseYear: '2008',
    rating: 8.5,
    voteCount: 32100,
    genreIds: [28, 80, 18],
    mediaType: 'movie',
    trailerKey: 'EXeTwQWrcwY',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 13,
    title: 'Forrest Gump',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events — in each case, far exceeding what anyone imagined he could do.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    releaseYear: '1994',
    rating: 8.5,
    voteCount: 26800,
    genreIds: [35, 18, 10749],
    mediaType: 'movie',
    trailerKey: 'bLvqoHBptjg',
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 120,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    overview: 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/pIUvQ9Ed35wlWhY2oU6OmwEgzx.jpg',
    releaseYear: '2001',
    rating: 8.4,
    voteCount: 24300,
    genreIds: [12, 14, 28],
    mediaType: 'movie',
    trailerKey: 'V75dMMIW2B4',
    providers: [],
  },
  {
    id: 603,
    title: 'The Matrix',
    overview: 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    releaseYear: '1999',
    rating: 8.2,
    voteCount: 25600,
    genreIds: [28, 878],
    mediaType: 'movie',
    trailerKey: 'vKQi3bBA1y8',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 429,
    title: 'The Good, the Bad and the Ugly',
    overview: 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hMnAJkf0K4VbhbcGiq7R3o6jnHR.jpg',
    releaseYear: '1966',
    rating: 8.5,
    voteCount: 8200,
    genreIds: [37],
    mediaType: 'movie',
    trailerKey: 'WCN5JJY_wiA',
    providers: [],
  },
  // TV Series
  {
    id: 1396,
    title: 'Breaking Bad',
    overview: 'When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live, he becomes filled with a sense of fearlessness.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseYear: '2008',
    rating: 8.9,
    voteCount: 13500,
    genreIds: [18, 80],
    mediaType: 'tv',
    trailerKey: 'HhesaQXLuRY',
    numberOfSeasons: 5,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 1399,
    title: 'Game of Thrones',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    releaseYear: '2011',
    rating: 8.4,
    voteCount: 22100,
    genreIds: [10765, 18, 10759],
    mediaType: 'tv',
    trailerKey: 'KPLWWIOCOOQ',
    numberOfSeasons: 8,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 66732,
    title: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/56v2KjBlYj4fOhLEnDAJZRLoAVb.jpg',
    releaseYear: '2016',
    rating: 8.6,
    voteCount: 17800,
    genreIds: [18, 10765, 9648],
    mediaType: 'tv',
    trailerKey: 'b9EkMc79ZSU',
    numberOfSeasons: 5,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 94605,
    title: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    releaseYear: '2021',
    rating: 8.7,
    voteCount: 4500,
    genreIds: [16, 10765, 10759],
    mediaType: 'tv',
    trailerKey: 'fXmAurh012s',
    numberOfSeasons: 2,
    providers: [
      { name: 'Netflix', logoUrl: 'https://image.tmdb.org/t/p/w92/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg' },
    ],
  },
  {
    id: 100088,
    title: 'The Last of Us',
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie out of an oppressive quarantine zone.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    releaseYear: '2023',
    rating: 8.6,
    voteCount: 5800,
    genreIds: [18, 10765],
    mediaType: 'tv',
    trailerKey: 'uLtkt8BonwM',
    numberOfSeasons: 2,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
  {
    id: 823464,
    title: 'Godzilla x Kong: The New Empire',
    overview: 'Following their fruit against Mechagodzilla, Godzilla and Kong make an uneasy truce. However a colossal undiscovered threat, hidden deep within our world, challenges their very existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDV4jC1kCTAM5BN.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg',
    releaseYear: '2024',
    rating: 7.1,
    voteCount: 5200,
    genreIds: [28, 878, 12],
    mediaType: 'movie',
    trailerKey: 'lV1OOlGwExM',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 572802,
    title: 'Aquaman and the Lost Kingdom',
    overview: 'Black Manta seeks revenge on Aquaman for the death of his father, while wielding the power of the mythic Black Trident. To defeat him, Aquaman turns to his imprisoned brother Orm.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8xV47NDrjdZDpkVcCFqkdHa3T5C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/cnqwv5Uz3UW5f086IWbQKr3yyJz.jpg',
    releaseYear: '2023',
    rating: 6.3,
    voteCount: 3800,
    genreIds: [28, 14, 12],
    mediaType: 'movie',
    trailerKey: 'UGc5Tzz19UY',
    providers: [],
  },
  {
    id: 76479,
    title: 'The Boys',
    overview: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers rather than using them for good.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9Ev8YwoozdMPcH8III.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7q448EVOnuE3gVAx24krzO7SNXM.jpg',
    releaseYear: '2019',
    rating: 8.5,
    voteCount: 10200,
    genreIds: [10765, 10759],
    mediaType: 'tv',
    trailerKey: 'tcrNsIaQkb4',
    numberOfSeasons: 4,
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    releaseYear: '2024',
    rating: 8.2,
    voteCount: 8100,
    genreIds: [878, 12],
    mediaType: 'movie',
    trailerKey: 'Way9Dexny3w',
    providers: [
      { name: 'Prime Video', logoUrl: 'https://image.tmdb.org/t/p/w92/emthp39XA2YScoYL1p0sdbAH2WA.jpg' },
    ],
  },
  {
    id: 114461,
    title: 'Ahsoka',
    overview: 'Former Jedi Knight Ahsoka Tano investigates an emerging threat to a vulnerable galaxy after the fall of the Galactic Empire.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/laCJxobHoPVaIMToJhkqYuXdPWV.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kUaFsOFtfCN3Jk2yP9GLnVr1CxI.jpg',
    releaseYear: '2023',
    rating: 7.4,
    voteCount: 2800,
    genreIds: [10765, 10759, 18],
    mediaType: 'tv',
    trailerKey: 'JDKc3eVTVmY',
    numberOfSeasons: 1,
    providers: [
      { name: 'Disney+', logoUrl: 'https://image.tmdb.org/t/p/w92/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg' },
    ],
  },
];

export function getMockContent(
  mediaType: 'movie' | 'tv' | 'all' = 'all',
  genreId?: number
): ContentItem[] {
  let filtered = MOCK_CONTENT;
  
  if (mediaType !== 'all') {
    filtered = filtered.filter(item => item.mediaType === mediaType);
  }
  
  if (genreId) {
    filtered = filtered.filter(item => item.genreIds.includes(genreId));
  }
  
  // Shuffle
  return [...filtered].sort(() => Math.random() - 0.5);
}
